### ISSUE TITLE
Calling the controller/method.

### ISSUE THREAD

**Issue by pedzed** [tres-framework/Tres-router#5]
We might have to change what we currently have:

``` php
Route::get('/users/:username/', [
    'controller' => 'UserController',
    'method' => 'getProfile'
]);
```

It makes the most of sense to do it this way, however, it's probably inefficient. Typing takes ages to be honest and it isn't too hard to understand Laravel's way of doing it:

``` php
Route::get('/users/:username/', [
    'uses' => 'UserController@getProfile'
]);
```

Should we change it? Not Laravel-like per se, but something easier to type.

@FireDart What do you think?

**Comment by pedzed** [comment]
What about the following?

``` php
Route::get('/users/:username/', [
    'uses' => 'UserController::getProfile'
]);
```

Would it give a bad feeling because it's not static per se? If yes, what about the following?

``` php
Route::get('/users/:username/', [
    'uses' => 'UserController.getProfile'
]);
```

**Comment by LukeXF** [comment]
Although the first example is much easier to begin with, I think the last one you listed .getprofile is probably a better to code quicker.

**Comment by julianrichen** [comment]
@pedzed You can always keep both of methods, however if I had to pick I would say the 'use' method using the @. The dot while clean blends in and could get lost easily, if you wan to use another character it has to really stand out.

For me the `/` or `>` stand out but the @ sign is far easier to read:

``` php
Route::get('/users/:username/', [
    'uses' => 'UserController/getProfile'
]);

Route::get('/users/:username/', [
    'uses' => 'UserController#getProfile'
]);

Route::get('/users/:username/', [
    'uses' => 'UserController>getProfile'
]);

Route::get('/users/:username/', [
    'uses' => 'UserController?getProfile'
]);

Route::get('/users/:username/', [
    'uses' => 'UserController;getProfile'
]);
```

**Comment by pedzed** [comment]
> You can always keep both of methods

Unless there is a good reason for it, I'd rather not. More flexibility means more documentation and more documentation is more reading. I doubt that people are interested in either of it.

We can always add it in the future, but removing it in the future will be a pain (backward compatibility).

P.S. What about `method``@``controller`?

``` php
Route::get('/users/:username/', [
    'uses' => 'getProfile@UserController'
]);
```

It makes more sense ("get profile method at/from the user controller"), but I don't think it types well.
